---
title       : "西村武司"
subtitle    : "Takeshi Nishimura"
author      : ""
date        : "Updated: `r Sys.Date()`"
about:
  license_file: LICENSE
output:
  xaringan::moon_reader:
    css: [metropolis, default, style.css]
    lib_dir: libs
    seal: false
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: '16:9'
---
# <svg width="35px" height="35px" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="id-badge" class="svg-inline--fa fa-id-badge fa-w-12" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512"><path fill="currentColor" d="M336 0H48C21.5 0 0 21.5 0 48v416c0 26.5 21.5 48 48 48h288c26.5 0 48-21.5 48-48V48c0-26.5-21.5-48-48-48zM144 32h96c8.8 0 16 7.2 16 16s-7.2 16-16 16h-96c-8.8 0-16-7.2-16-16s7.2-16 16-16zm48 128c35.3 0 64 28.7 64 64s-28.7 64-64 64-64-28.7-64-64 28.7-64 64-64zm112 236.8c0 10.6-10 19.2-22.4 19.2H102.4C90 416 80 407.4 80 396.8v-19.2c0-31.8 30.1-57.6 67.2-57.6h5c12.3 5.1 25.7 8 39.8 8s27.6-2.9 39.8-8h5c37.1 0 67.2 25.8 67.2 57.6v19.2z"></path></svg>
## 西村武司 / Takeshi Nishimura

- [researchmap](https://researchmap.jp/takeshinishimura)
- [Google Scholar](https://scholar.google.com/citations?user=wPs3Y6QAAAAJ)
- [ORCID](https://orcid.org/0000-0003-1761-4300)

[<svg width="15px" height="15px" aria-hidden="true" focusable="false" data-prefix="far" data-icon="paper-plane" class="svg-inline--fa fa-paper-plane fa-w-16" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M440 6.5L24 246.4c-34.4 19.9-31.1 70.8 5.7 85.9L144 379.6V464c0 46.4 59.2 65.5 86.6 28.6l43.8-59.1 111.9 46.2c5.9 2.4 12.1 3.6 18.3 3.6 8.2 0 16.3-2.1 23.6-6.2 12.8-7.2 21.6-20 23.9-34.5l59.4-387.2c6.1-40.1-36.9-68.8-71.5-48.9zM192 464v-64.6l36.6 15.1L192 464zm212.6-28.7l-153.8-63.5L391 169.5c10.7-15.5-9.5-33.5-23.7-21.2L155.8 332.6 48 288 464 48l-59.4 387.3z"></path></svg> t&#97;&#107;&#101;ni&#115;&#104;i&#64;&#103;&#109;&#97;&#105;&#108;&#46;&#99;om](mailto:t&#97;&#107;&#101;ni&#115;&#104;i&#64;&#103;&#109;&#97;&#105;&#108;&#46;&#99;om)


---
# Location

```{r results = "markup", echo = FALSE, fig.height = 7.5, fig.width = 15, out.width = '100%', fig.align = "center"}
library(leaflet)
m <- leaflet() %>% addTiles()
m %>% setView(lng = 133.935, lat = 34.66167, zoom = 9) %>%
  addPopups(lng = 133.935, lat = 34.66167, popup = "Okayama, Japan") %>%
  addMiniMap(position = "bottomright")
```


---
# Mac computers

## Laptop
- [MacBook Air (M1, 2020)](https://support.apple.com/kb/SP825) <- macOS Big Sur
- [MacBook Air (Retina, 13-inch, 2020)](https://support.apple.com/kb/SP813) <- macOS Big Sur- [MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports)](https://support.apple.com/kb/SP755) <- macOS Big Sur- [MacBook Air (11-inch, Early 2015)](https://support.apple.com/kb/SP713) <- macOS Big Sur- [MacBook Pro (Retina, 13-inch, Late 2013)](https://support.apple.com/kb/SP691) <- macOS Mojave- [MacBook Air (13-inch, Mid 2012)](https://support.apple.com/kb/SP670) <- macOS Catalina- [MacBook Pro (13-inch, Late 2011)](https://support.apple.com/kb/SP645) <- macOS Mojave- [MacBook Pro (13-inch, Mid 2009)](https://support.apple.com/kb/SP541) <- OS X Yosemite- iBook (FireWire SE) <- Mac OS X 10.3 (Panther)

### List
- [Identify your MacBook Pro model](https://support.apple.com/en-us/HT201300)
- [Identify your MacBook Air model](https://support.apple.com/en-us/HT201862)


---
# Mac computers

## Desktop
- [Mac Pro (Late 2013)](https://support.apple.com/kb/SP697) <- macOS Big Sur- [Mac mini (Late 2012)](https://support.apple.com/kb/SP659) <- macOS Catalina- [iMac (20-inch, Early 2006)](https://www.apple.com/jp/support/datasheet/imac/imac_710_590_589.html) <- Mac OS X 10.6 (Snow Leopard)- [Mac mini (Early 2005)](https://www.apple.com/jp/support/datasheet/desktop/macmini_9686879971.html) <- Mac OS X 10.4 (Tiger)

### List
- [Identify your Mac Pro model](https://support.apple.com/en-us/HT202888)
- [Identify your iMac model](https://support.apple.com/en-us/HT201634)- [Identify your Mac mini model](https://support.apple.com/en-us/HT201894)


---
# iPads

- [iPad Air (4th generation)](https://support.apple.com/kb/SP828) <- iPadOS 14
- [iPad Pro (9.7-inch)](https://support.apple.com/kb/SP739) <- iPadOS 14
- [iPad mini 3](https://support.apple.com/kb/SP709) <- iPadOS 12.5
- [iPad Air](https://support.apple.com/kb/SP692) <- iPadOS 12.5
- [iPad (3rd generation)](https://support.apple.com/kb/SP647) <- iOS 9.3.5
- [iPad mini](https://support.apple.com/kb/SP661) <- iOS 9.3.5
- [iPad 2](https://support.apple.com/kb/sp622) <- iOS 6.1.3
- [iPad](https://support.apple.com/kb/SP580) <- iOS 5.1.1

### List
- [Identify your iPad model](https://support.apple.com/en-us/HT201471)


---
# Presentations

## LaTeX Beamer
- [Beamer](https://ctan.org/pkg/beamer)
- [Metropolis](https://github.com/matze/mtheme)
  + XeLaTeXでコンパイル

```TeX
\documentclass[unicode, 10pt, xcolor={dvipsnames, svgnames}, usepdftitle=false]{beamer}
% ハンドアウトの場合：handout
% 16:9の場合：aspectratio=169
\usetheme{metropolis}

% 日本語対応
\usepackage{zxjatype}
\setjamainfont{Hiragino Mincho ProN W3}
\setjasansfont{Hiragino Kaku Gothic ProN W3}
\setjamonofont{Hiragino Kaku Gothic ProN W3}

%\usepackage{arev}% 数式フォントをArev Sansなどにすると，記号（例：※，→）が出力されない
```


---
# Presentations

## R Markdown
- [xaringan](https://github.com/yihui/xaringan)

```r
install.packages("xaringan")

library(rmarkdown)
rmarkdown::render("index.Rmd")
browseURL("index.html")
```

- [Slidify](https://github.com/ramnathv/slidify)

```r
require(devtools)
devtools::install_github("ramnathv/slidify")
devtools::install_github("ramnathv/slidifyLibraries")

library(slidify)
slidify::author("slidify")
slidify::slidify("index.Rmd")
browseURL("index.html")
```
